"""Writes tests/prop_types.lua: the REAL value type of every Roblox property the UI script uses, taken from Roblox's API dump.
The smoke test uses it to reject wrong-typed assignments (e.g. Parent = 40, Text = 5, Size = Color3) exactly like Roblox would.
  python3 tools/gen_prop_types.py API-Dump.json ../tsb_animation_hub.lua > tests/prop_types.lua"""
import json, re, sys
dump = json.load(open(sys.argv[1]))
src = open(sys.argv[2], encoding="utf-8").read()
classes = {c["Name"]: c for c in dump["Classes"]}
used = set(re.findall(r'\bnew\("([A-Za-z]+)"', src)) | set(re.findall(r'Instance\.new\("([A-Za-z]+)"', src))
used = sorted(u for u in used if u in classes)
words = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", src))
print("-- generated by tools/gen_prop_types.py from Roblox's API dump - do not edit")
print("return {")
for u in used:
    props, chain, c = {}, [], u
    while c and c in classes:
        chain.append(c); c = classes[c].get("Superclass")
    for name in chain:
        for m in classes[name]["Members"]:
            if m["MemberType"] == "Property" and m["Name"] in words and m["Name"] not in props:
                vt = m["ValueType"]
                if vt["Category"] == "Enum": kind = "Enum:" + vt["Name"]
                elif vt["Category"] == "Class": kind = "Instance"
                else: kind = vt["Name"]
                props[m["Name"]] = kind
    print("  %s = {%s}," % (u, ", ".join('%s = "%s"' % (k, v) for k, v in sorted(props.items()))))
print("}")
