"""Writes tests/prop_types_mm2.lua: for every Roblox class the MM2 hub touches, its real properties (with value types), methods, events and
superclass chain, taken from Roblox's API dump. The fake Roblox world in tests/mm2_env.lua uses it to throw like Roblox does when the script
reads a member that does not exist, assigns a wrong-typed value, or calls a method the class does not have.
  python3 tools/gen_member_types.py API-Dump.json mm2/ui_lib.lua mm2/wraiths_hub.lua -- Part Humanoid ... > tests/prop_types_mm2.lua
Classes = every Instance.new("X") / mk("X", ...) in the given sources (with --quoted: every string literal that is a class name) + the extra classes after `--`.
Only members whose name occurs as a word in the sources are listed (everything else is irrelevant to this script)."""
import json, re, sys
args = sys.argv[1:]
dump = json.load(open(args[0]))
rest = args[1:]
quoted = "--quoted" in rest            # also every "ClassName" string literal (needed for libraries that call New("Frame", ...))
rest = [r for r in rest if r != "--quoted"]
extra = []
if "--" in rest:
    i = rest.index("--"); extra = rest[i + 1:]; rest = rest[:i]
src = "\n".join(open(p, encoding="utf-8").read() for p in rest)
classes = {c["Name"]: c for c in dump["Classes"]}
used = set(re.findall(r'Instance\.new\("([A-Za-z0-9]+)"', src)) | set(re.findall(r'\bmk\("([A-Za-z0-9]+)"', src)) | set(extra)
if quoted: used |= set(re.findall(r'["\']([A-Za-z0-9]+)["\']', src))
used = sorted(u for u in used if u in classes)
words = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", src))
supers, out = {}, []
for u in used:
    props, fns, evs, chain, c = {}, {}, {}, [], u
    while c and c in classes:
        chain.append(c)
        if classes[c].get("Superclass") and classes[c]["Superclass"] != "<<<ROOT>>>":
            supers[c] = classes[c]["Superclass"]
        c = classes[c].get("Superclass")
    for name in chain:
        for m in classes[name]["Members"]:
            if m["Name"] not in words: continue
            if m["MemberType"] == "Property":
                vt = m["ValueType"]
                kind = ("Enum:" + vt["Name"]) if vt["Category"] == "Enum" else "Instance" if vt["Category"] == "Class" else vt["Name"]
                props.setdefault(m["Name"], kind)
            elif m["MemberType"] == "Function": fns.setdefault(m["Name"], True)
            elif m["MemberType"] == "Event": evs.setdefault(m["Name"], True)
    fmt = lambda d, v: ", ".join('%s = %s' % (k, ('"%s"' % x) if isinstance(x, str) else "true") for k, x in sorted(d.items()))
    out.append("    %s = {props = {%s}, fns = {%s}, evs = {%s}}," % (u, fmt(props, 0), fmt(fns, 0), fmt(evs, 0)))
print("-- generated by tools/gen_member_types.py from Roblox's API dump - do not edit")
print("return {")
print("  supers = {%s}," % ", ".join('%s = "%s"' % (k, v) for k, v in sorted(supers.items())))
print("  classes = {")
print("\n".join(out))
print("  },")
print("}")
